test:
  adapter: postgresql
  encoding: unicode
  database: pg_test
  pool: 5
  username: postgres
  password: macbook88
  timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: pg_dev
  pool: 5
  username: postgres
  password: macbook88
  timeout: 5000

production:
  adapter: sqlite3
  database: db/production.sqlite3
  pool: 5
  timeout: 5000
